[project]
name = "rag-two-branch"
version = "0.1.0"
description = "RAG 비법노트 심화편 내용을 활용한 프로젝트 실습"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-text-splitters",
    "faiss-cpu",
    "pypdf",
    "langchain-classic",
    "sentence-transformers",
]

[dependency-groups]
dev = [
    "ipykernel",
]

[tool.uv]
package = false
